export const ADD_SUBJECT_REQUEST = 'ADD_SUBJECT_REQUEST'
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS'
export const ADD_SUBJECT_FAIL = 'ADD_SUBJECT_FAIL'
export const ADD_SUBJECT_RESET = 'ADD_SUBJECT_RESET'

export const LIST_SUBJECT_REQUEST = 'LIST_SUBJECT_REQUEST'
export const LIST_SUBJECT_SUCCESS = 'LIST_SUBJECT_SUCCESS'
export const LIST_SUBJECT_FAIL = 'ADD_SUBJECT_FAIL'
export const LIST_SUBJECT_RESET = 'LIST_SUBJECT_RESET'

export const UPDATE_SUBJECT_REQUEST = 'UPDATE_SUBJECT_REQUEST'
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS'
export const UPDATE_SUBJECT_FAIL = 'UPDATE_SUBJECT_FAIL'
export const UPDATE_SUBJECT_RESET = 'UPDATE_SUBJECT_RESET'

export const DELETE_SUBJECT_REQUEST = 'DELETE_SUBJECT_REQUEST'
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS'
export const DELETE_SUBJECT_FAIL = 'DELETE_SUBJECT_FAIL'
export const DELETE_SUBJECT_RESET = 'DELETE_SUBJECT_RESET'

export const DETAIL_SUBJECT_REQUEST = 'DETAIL_SUBJECT_REQUEST'
export const DETAIL_SUBJECT_SUCCESS = 'DETAIL_SUBJECT_SUCCESS'
export const DETAIL_SUBJECT_FAIL = 'DETAIL_SUBJECT_FAIL'
export const DETAIL_SUBJECT_RESET = 'DETAIL_SUBJECT_RESET'

export const GET_TOPIC_REQUEST = 'GET_TOPIC_REQUEST'
export const GET_TOPIC_SUCCESS = 'GET_TOPIC_SUCCESS'
export const GET_TOPIC_FAIL = 'GET_TOPIC_FAIL'
export const GET_TOPIC_RESET = 'GET_TOPIC_RESET'

export const ADD_TOPIC_REQUEST = 'ADD_TOPIC_REQUEST'
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS'
export const ADD_TOPIC_FAIL = 'ADD_TOPIC_FAIL'
export const ADD_TOPIC_RESET = 'ADD_TOPIC_RESET'

export const UPDATE_TOPIC_REQUEST = 'UPDATE_TOPIC_REQUEST'
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS'
export const UPDATE_TOPIC_FAIL = 'UPDATE_TOPIC_FAIL'
export const UPDATE_TOPIC_RESET = 'UPDATE_TOPIC_RESET'

export const DELETE_TOPIC_REQUEST = 'DELETE_TOPIC_REQUEST'
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS'
export const DELETE_TOPIC_FAIL = 'DELETE_TOPIC_FAIL'
export const DELETE_TOPIC_RESET = 'DELETE_TOPIC_RESET'

export const ADD_NOTE_REQUEST = 'ADD_NOTE_REQUEST'
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL'
export const ADD_NOTE_RESET = 'ADD_NOTE_RESET'

export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST'
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS'
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL'
export const UPDATE_NOTE_RESET = 'UPDATE_NOTE_RESET'

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL'
export const DELETE_NOTE_RESET = 'DELETE_NOTE_RESET'
