export const ADD_SUBJECT_REQUEST = 'ADD_SUBJECT_REQUEST'
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS'
export const ADD_SUBJECT_FAIL = 'ADD_SUBJECT_FAIL'
export const ADD_SUBJECT_RESET = 'ADD_SUBJECT_RESET'

export const LIST_SUBJECT_REQUEST = 'LIST_SUBJECT_REQUEST'
export const LIST_SUBJECT_SUCCESS = 'LIST_SUBJECT_SUCCESS'
export const LIST_SUBJECT_FAIL = 'ADD_SUBJECT_FAIL'
export const LIST_SUBJECT_RESET = 'LIST_SUBJECT_RESET'

export const UPDATE_SUBJECT_REQUEST = 'UPDATE_SUBJECT_REQUEST'
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS'
export const UPDATE_SUBJECT_FAIL = 'UPDATE_SUBJECT_FAIL'
export const UPDATE_SUBJECT_RESET = 'UPDATE_SUBJECT_RESET'

export const DELETE_SUBJECT_REQUEST = 'DELETE_SUBJECT_REQUEST'
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS'
export const DELETE_SUBJECT_FAIL = 'DELETE_SUBJECT_FAIL'
export const DELETE_SUBJECT_RESET = 'DELETE_SUBJECT_RESET'

export const DETAIL_SUBJECT_REQUEST = 'DETAIL_SUBJECT_REQUEST'
export const DETAIL_SUBJECT_SUCCESS = 'DETAIL_SUBJECT_SUCCESS'
export const DETAIL_SUBJECT_FAIL = 'DETAIL_SUBJECT_FAIL'
export const DETAIL_SUBJECT_RESET = 'DETAIL_SUBJECT_RESET'
